build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

filter:
  dependency_paths:
    - vendor/

tools:
  external_code_coverage: true
  # timeout: 600 # default timeout in seconds
